title: Currency Guide
description: A guide to make currency in POE
theme: just-the-docs

url: https://imviktor.github.io/jekyll-poe-guide/

# Aux links for the upper right navigation
aux_links:
  "Path of Exile":
    - "https://www.pathofexile.com/"
  "PoE Trade":
    - "https://www.pathofexile.com/trade"

aux_links_new_tab: true

logo: "/assets/images/logo.png"

# Color scheme supports "light" (default) and "dark"
# color_scheme: dark

callouts:
  warning:
    title: Warning
    color: red